const { getDefaultConfig } = require('./themeDefaults');

const presets = [
  {
    id: 'clean-modern',
    name: 'Clean Modern',
    description: 'White background with a vibrant blue primary. Rounded corners, multi-step flow.',
    previewColors: { primary: '#3B82F6', background: '#FFFFFF', accent: '#3B82F6' },
    config: {
      ...getDefaultConfig(),
      colors: {
        ...getDefaultConfig().colors,
        primary: '#3B82F6',
        buttonBg: '#3B82F6',
        accent: '#3B82F6',
        selectedBg: '#3B82F6',
        todayRing: '#3B82F6',
      },
      typography: {
        fontFamily: "'Inter', sans-serif",
        headingSize: '18px',
        bodySize: '14px',
        smallSize: '12px',
        fontWeight: '500',
        headingWeight: '600',
      },
      spacing: { borderRadius: 10, padding: 16, gap: 8, slotPadding: 10 },
      layout: { type: 'multi-step', stepsOrder: ['calendar', 'time', 'form', 'confirm'] },
    },
  },
  {
    id: 'dark-professional',
    name: 'Dark Professional',
    description: 'Dark background with a purple accent. Sharp, modern look for professional services.',
    previewColors: { primary: '#8B5CF6', background: '#1A1A2E', accent: '#8B5CF6' },
    config: {
      ...getDefaultConfig(),
      colors: {
        primary: '#8B5CF6',
        background: '#1A1A2E',
        text: '#E2E8F0',
        textMuted: '#94A3B8',
        buttonBg: '#8B5CF6',
        buttonText: '#FFFFFF',
        accent: '#8B5CF6',
        border: '#334155',
        hoverBg: '#2D2D44',
        selectedBg: '#8B5CF6',
        selectedText: '#FFFFFF',
        todayRing: '#8B5CF6',
        shadow: 'rgba(0,0,0,0.3)',
        error: '#F87171',
        success: '#4ADE80',
      },
      typography: {
        fontFamily: "'DM Sans', sans-serif",
        headingSize: '18px',
        bodySize: '14px',
        smallSize: '12px',
        fontWeight: '500',
        headingWeight: '600',
      },
      spacing: { borderRadius: 6, padding: 16, gap: 8, slotPadding: 10 },
      layout: { type: 'multi-step', stepsOrder: ['calendar', 'time', 'form', 'confirm'] },
    },
  },
  {
    id: 'warm-friendly',
    name: 'Warm & Friendly',
    description: 'Cream background with a warm orange primary. Rounded, approachable, larger text.',
    previewColors: { primary: '#F97316', background: '#FFFBF5', accent: '#F97316' },
    config: {
      ...getDefaultConfig(),
      colors: {
        primary: '#F97316',
        background: '#FFFBF5',
        text: '#292524',
        textMuted: '#78716C',
        buttonBg: '#F97316',
        buttonText: '#FFFFFF',
        accent: '#F97316',
        border: '#E7E5E4',
        hoverBg: '#FFF7ED',
        selectedBg: '#F97316',
        selectedText: '#FFFFFF',
        todayRing: '#F97316',
        shadow: 'rgba(0,0,0,0.06)',
        error: '#EF4444',
        success: '#22C55E',
      },
      typography: {
        fontFamily: "'Poppins', sans-serif",
        headingSize: '20px',
        bodySize: '15px',
        smallSize: '13px',
        fontWeight: '400',
        headingWeight: '600',
      },
      spacing: { borderRadius: 12, padding: 20, gap: 10, slotPadding: 12 },
      layout: { type: 'multi-step', stepsOrder: ['calendar', 'time', 'form', 'confirm'] },
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean white with thin black borders, no rounded corners. Single-page layout.',
    previewColors: { primary: '#18181B', background: '#FFFFFF', accent: '#18181B' },
    config: {
      ...getDefaultConfig(),
      colors: {
        primary: '#18181B',
        background: '#FFFFFF',
        text: '#18181B',
        textMuted: '#71717A',
        buttonBg: '#18181B',
        buttonText: '#FFFFFF',
        accent: '#18181B',
        border: '#D4D4D8',
        hoverBg: '#F4F4F5',
        selectedBg: '#18181B',
        selectedText: '#FFFFFF',
        todayRing: '#18181B',
        shadow: 'rgba(0,0,0,0.04)',
        error: '#EF4444',
        success: '#22C55E',
      },
      typography: {
        fontFamily: "'Inter', sans-serif",
        headingSize: '16px',
        bodySize: '13px',
        smallSize: '11px',
        fontWeight: '400',
        headingWeight: '500',
      },
      spacing: { borderRadius: 0, padding: 16, gap: 6, slotPadding: 8 },
      layout: { type: 'single-page', stepsOrder: ['calendar', 'time', 'form', 'confirm'] },
      components: {
        ...getDefaultConfig().components,
        showProgressBar: false,
        showPoweredBy: false,
      },
    },
  },
  {
    id: 'bold-brand',
    name: 'Bold Brand',
    description: 'Vibrant emerald with large CTA buttons and pill-shaped time slots.',
    previewColors: { primary: '#10B981', background: '#FFFFFF', accent: '#10B981' },
    config: {
      ...getDefaultConfig(),
      colors: {
        primary: '#10B981',
        background: '#FFFFFF',
        text: '#111827',
        textMuted: '#6B7280',
        buttonBg: '#10B981',
        buttonText: '#FFFFFF',
        accent: '#10B981',
        border: '#D1FAE5',
        hoverBg: '#ECFDF5',
        selectedBg: '#10B981',
        selectedText: '#FFFFFF',
        todayRing: '#10B981',
        shadow: 'rgba(16,185,129,0.12)',
        error: '#EF4444',
        success: '#10B981',
      },
      typography: {
        fontFamily: "'DM Sans', sans-serif",
        headingSize: '20px',
        bodySize: '15px',
        smallSize: '12px',
        fontWeight: '500',
        headingWeight: '700',
      },
      spacing: { borderRadius: 16, padding: 20, gap: 10, slotPadding: 12 },
      timeSlots: { style: 'pills', columns: 3 },
      layout: { type: 'multi-step', stepsOrder: ['calendar', 'time', 'form', 'confirm'] },
    },
  },
];

module.exports = { presets };
